-- ═══════════════════════════════════════════════════════════════════
--  Sitycom — مخطط قاعدة البيانات على Supabase (PostgreSQL)
--
--  طريقة الاستعمال (مرة واحدة فقط):
--  1) افتح مشروعك على Supabase ← SQL Editor ← New query
--  2) الصق هذا الملف كاملاً ← Run
--  3) شغّل الخادم:  npm install && npm start
--     (ينشئ الخادم المستخدم الإداري والبيانات التجريبية تلقائياً)
-- ═══════════════════════════════════════════════════════════════════

-- ── الجداول ─────────────────────────────────────────────────────────

create table if not exists public.users (
  id            bigint generated by default as identity primary key,
  username      text not null unique,
  name          text not null,
  password_hash text not null,
  role          text not null default 'admin',
  active        smallint not null default 1,
  last_login    text,
  created_at    text not null
);

create table if not exists public.sessions (
  token      text primary key,
  user_id    bigint not null references public.users (id) on delete cascade,
  expires_at text not null,
  created_at text not null
);
create index if not exists idx_sessions_user on public.sessions (user_id);

create table if not exists public.settings (
  key        text primary key,
  value      text,
  updated_at text
);

create table if not exists public.categories (
  id         bigint generated by default as identity primary key,
  name_ar    text not null,
  name_fr    text not null default '',
  name_en    text not null default '',
  slug       text,
  active     smallint not null default 1,
  created_at text not null
);

create table if not exists public.products (
  id                 bigint generated by default as identity primary key,
  sku                text,
  name_ar            text not null,
  name_fr            text not null default '',
  name_en            text not null default '',
  description        text default '',
  price              double precision not null default 0,
  cost               double precision not null default 0,
  stock              integer not null default 0,
  category_id        bigint references public.categories (id) on delete set null,
  image_url          text default '',
  weight             double precision default 0,
  fragile            smallint not null default 0,
  ecotrack_reference text default '',
  active             smallint not null default 1,
  created_at         text not null,
  updated_at         text not null
);
create index if not exists idx_products_sku on public.products (sku);
create index if not exists idx_products_category on public.products (category_id);

create table if not exists public.customers (
  id         bigint generated by default as identity primary key,
  name       text not null,
  phone      text not null unique,
  phone2     text default '',
  email      text default '',
  wilaya_id  integer,
  commune    text default '',
  address    text default '',
  notes      text default '',
  created_at text not null
);

create table if not exists public.orders (
  id             bigint generated by default as identity primary key,
  order_number   text not null unique,
  customer_id    bigint,
  customer_name  text not null,
  phone          text not null,
  phone2         text default '',
  wilaya_id      integer,
  wilaya_name    text default '',
  commune        text default '',
  address        text default '',
  stop_desk      smallint not null default 0,
  desk_code      text default '',
  desk_name      text default '',
  subtotal       double precision not null default 0,
  shipping_fee   double precision not null default 0,
  discount       double precision not null default 0,
  total          double precision not null default 0,
  status         text not null default 'draft',
  payment_status text not null default 'unpaid',
  source         text not null default 'admin',
  notes          text default '',
  created_at     text not null,
  updated_at     text not null
);
create index if not exists idx_orders_status on public.orders (status);
create index if not exists idx_orders_created on public.orders (created_at);

create table if not exists public.order_items (
  id         bigint generated by default as identity primary key,
  order_id   bigint not null references public.orders (id) on delete cascade,
  product_id bigint,
  name       text not null,
  sku        text default '',
  qty        integer not null default 1,
  unit_price double precision not null default 0,
  line_total double precision not null default 0
);
create index if not exists idx_items_order on public.order_items (order_id);

create table if not exists public.shipments (
  id                  bigint generated by default as identity primary key,
  order_id            bigint not null unique references public.orders (id) on delete cascade,
  tracking            text,
  reference           text,
  type                integer not null default 1,   -- 1 Livraison 2 Échange 3 Pickup 4 Recouvrement
  stop_desk           smallint not null default 0,
  produit             text default '',
  quantite            text default '',
  stock               smallint not null default 0,
  produit_a_recuperer text default '',
  boutique            text default '',
  remarque            text default '',
  weight              double precision default 0,
  fragile             smallint not null default 0,
  gps_link            text default '',
  ask_collection      smallint not null default 0,
  ecotrack_status     text default '',
  delivery_fee        double precision default 0,
  return_fee          double precision default 0,
  last_activity       text default '',
  last_activity_at    text default '',
  pushed_at           text,
  validated_at        text,
  return_asked_at     text,
  synced_at           text,
  raw                 text
);
create index if not exists idx_shipments_tracking on public.shipments (tracking);

create table if not exists public.order_events (
  id         bigint generated by default as identity primary key,
  order_id   bigint references public.orders (id) on delete cascade,
  tracking   text,
  status     text,
  activity   text,
  station    text default '',
  driver     text default '',
  details    text default '',
  event_date text,
  event_time text,
  created_at text not null
);
create index if not exists idx_events_order on public.order_events (order_id);
create index if not exists idx_events_tracking on public.order_events (tracking);

create table if not exists public.wilayas (
  wilaya_id     integer primary key,
  name_fr       text not null,
  name_ar       text not null default '',
  active        smallint not null default 1,
  has_stop_desk smallint not null default 0,
  synced_at     text
);

create table if not exists public.communes (
  id            bigint generated by default as identity primary key,
  wilaya_id     integer not null,
  name          text not null,
  code_postal   text default '',
  has_stop_desk smallint not null default 0,
  unique (wilaya_id, name)
);
create index if not exists idx_communes_wilaya on public.communes (wilaya_id);

create table if not exists public.desks (
  id         bigint generated by default as identity primary key,
  hub_id     text,
  name       text not null,
  wilaya     text default '',
  commune    text default '',
  address    text default '',
  phone      text default '',
  phone2     text default '',
  email      text default '',
  map        text default '',
  hours      text default '',
  is_my_desk smallint not null default 0
);

create table if not exists public.shipping_fees (
  wilaya_id           integer primary key,
  wilaya_name         text default '',
  delivery_home       double precision not null default 0,
  delivery_stopdesk   double precision not null default 0,
  pickup_home         double precision not null default 0,
  pickup_stopdesk     double precision not null default 0,
  exchange_home       double precision not null default 0,
  exchange_stopdesk   double precision not null default 0,
  collection_home     double precision not null default 0,
  collection_stopdesk double precision not null default 0,
  return_home         double precision not null default 0,
  return_stopdesk     double precision not null default 0,
  raw                 text,
  synced_at           text
);

create table if not exists public.ecotrack_products (
  reference        text primary key,
  barcode          text default '',
  title            text default '',
  is_active        smallint not null default 1,
  image            text default '',
  stock_disponible integer default 0,
  stock_reserve    integer default 0,
  stock_phisique   integer default 0,
  synced_at        text
);

create table if not exists public.activity_log (
  id         bigint generated by default as identity primary key,
  user_id    bigint,
  username   text default '',
  action     text not null,
  entity     text default '',
  entity_id  text default '',
  details    text default '',
  ok         smallint not null default 1,
  created_at text not null
);
create index if not exists idx_log_created on public.activity_log (created_at);

create table if not exists public.sync_jobs (
  id          bigint generated by default as identity primary key,
  kind        text not null,
  status      text not null,
  message     text default '',
  count       integer default 0,
  started_at  text not null,
  finished_at text
);

-- ── الأذونات (يستخدم الخادم مفتاح anon) ────────────────────────────

grant usage on schema public to anon, authenticated;
grant all privileges on all tables in schema public to anon, authenticated;
grant all privileges on all sequences in schema public to anon, authenticated;
alter default privileges in schema public grant all privileges on tables to anon, authenticated;
alter default privileges in schema public grant all privileges on sequences to anon, authenticated;

-- ── سياسة أمان واحدة لكل الجداول (تطبيق داخلي بمفتاح الخادم) ──────

do $$
declare t text;
begin
  foreach t in array array[
    'users','sessions','settings','categories','products','customers','orders',
    'order_items','shipments','order_events','wilayas','communes','desks',
    'shipping_fees','ecotrack_products','activity_log','sync_jobs'
  ]
  loop
    execute format('alter table public.%I enable row level security', t);
    execute format('drop policy if exists %I on public.%I', t || '_app_access', t);
    execute format(
      'create policy %I on public.%I for all to anon, authenticated using (true) with check (true)',
      t || '_app_access', t);
  end loop;
end $$;

-- ── دوال مساعدة: الآن بنص يطابق صيغة التطبيق ──────────────────────

create or replace function public.app_now()
returns text
language sql stable
as $$ select to_char(now(), 'YYYY-MM-DD HH24:MI:SS') $$;

-- ═══════════════════════════════════════════════════════════════════
--  دوال التجميع (تُستدعى عبر  supabase.rpc)
-- ═══════════════════════════════════════════════════════════════════

-- ── لوحة المعلومات ──────────────────────────────────────────────────
create or replace function public.dashboard_data(p_days integer default 30)
returns jsonb
language plpgsql stable
as $$
declare
  v_since text;
begin
  v_since := to_char(now() - make_interval(days => p_days), 'YYYY-MM-DD HH24:MI:SS');
  return jsonb_build_object(
    'cards', jsonb_build_object(
      'orders',        (select count(*) from public.orders where created_at >= v_since),
      'revenue',       coalesce((select sum(total) from public.orders where created_at >= v_since), 0),
      'shipping',      coalesce((select sum(shipping_fee) from public.orders where created_at >= v_since), 0),
      'discount',      coalesce((select sum(discount) from public.orders where created_at >= v_since), 0),
      'pending',       (select count(*) from public.orders where status in ('draft','prete_a_expedier','en_preparation','en_preparation_stock')),
      'in_transit',    (select count(*) from public.orders where status in ('en_ramassage','vers_hub','en_hub','vers_wilaya','en_livraison')),
      'delivered',     (select count(*) from public.orders where status in ('livre_non_encaisse','encaisse_non_paye','paiements_prets','paye_et_archive')),
      'returns',       (select count(*) from public.orders where status like 'retour%'),
      'suspended',     (select count(*) from public.orders where status = 'suspendu'),
      'not_pushed',    (select count(*) from public.orders o left join public.shipments s on s.order_id = o.id
                          where s.tracking is null or s.tracking = ''),
      'collected',     coalesce((select sum(total) from public.orders where status in ('encaisse_non_paye','paiements_prets','paye_et_archive')), 0),
      'customers',     (select count(*) from public.customers),
      'new_customers', (select count(*) from public.customers where created_at >= v_since)
    ),
    'statusCounts', coalesce((
      select jsonb_agg(jsonb_build_object('status', t.st, 'count', t.c) order by t.c desc)
      from (select coalesce(s.ecotrack_status, o.status) as st, count(*) as c
            from public.orders o left join public.shipments s on s.order_id = o.id
            group by 1) t
    ), '[]'::jsonb),
    'daily', coalesce((
      select jsonb_agg(jsonb_build_object('day', t.day, 'orders', t.orders, 'revenue', t.revenue) order by t.day)
      from (select left(created_at, 10) as day, count(*) as orders, coalesce(sum(total), 0) as revenue
            from public.orders where created_at >= v_since group by 1) t
    ), '[]'::jsonb),
    'topWilayas', coalesce((
      select jsonb_agg(jsonb_build_object('wilaya_id', t.wilaya_id, 'wilaya_name', t.wilaya_name,
                                          'orders', t.orders, 'revenue', t.revenue) order by t.orders desc)
      from (select o.wilaya_id, o.wilaya_name, count(*) as orders, coalesce(sum(o.total), 0) as revenue
            from public.orders o where o.created_at >= v_since
            group by o.wilaya_id, o.wilaya_name order by orders desc limit 8) t
    ), '[]'::jsonb),
    'topProducts', coalesce((
      select jsonb_agg(jsonb_build_object('name', t.name, 'qty', t.qty, 'revenue', t.revenue) order by t.qty desc)
      from (select oi.name, sum(oi.qty) as qty, coalesce(sum(oi.line_total), 0) as revenue
            from public.order_items oi join public.orders o on o.id = oi.order_id
            where o.created_at >= v_since group by oi.name order by qty desc limit 8) t
    ), '[]'::jsonb),
    'recent', coalesce((
      select jsonb_agg(jsonb_build_object(
        'id', t.id, 'order_number', t.order_number, 'customer_name', t.customer_name,
        'phone', t.phone, 'wilaya_name', t.wilaya_name, 'total', t.total, 'status', t.status,
        'created_at', t.created_at, 'tracking', t.tracking, 'ecotrack_status', t.ecotrack_status
      ) order by t.id desc)
      from (select o.id, o.order_number, o.customer_name, o.phone, o.wilaya_name, o.total, o.status,
                   o.created_at, s.tracking, s.ecotrack_status
            from public.orders o left join public.shipments s on s.order_id = o.id
            order by o.id desc limit 10) t
    ), '[]'::jsonb),
    'lowStock', coalesce((
      select jsonb_agg(jsonb_build_object('id', id, 'name_ar', name_ar, 'sku', sku, 'stock', stock) order by stock asc)
      from (select id, name_ar, sku, stock from public.products
            where active = 1 and stock <= 5 order by stock asc limit 8) t
    ), '[]'::jsonb)
  );
end $$;

-- ── التقارير المفصّلة ───────────────────────────────────────────────
create or replace function public.reports_data(p_from text, p_to text)
returns jsonb
language plpgsql stable
as $$
begin
  return jsonb_build_object(
    'summary', coalesce((
      select jsonb_build_object('orders', count(*), 'revenue', coalesce(sum(total), 0),
        'shipping', coalesce(sum(shipping_fee), 0), 'discount', coalesce(sum(discount), 0),
        'avg_order', coalesce(avg(total), 0))
      from public.orders where left(created_at, 10) between p_from and p_to
    ), '{}'::jsonb),
    'byDay', coalesce((
      select jsonb_agg(jsonb_build_object('day', t.day, 'orders', t.orders, 'revenue', t.revenue,
                                          'shipping', t.shipping) order by t.day)
      from (select left(created_at, 10) as day, count(*) as orders, coalesce(sum(total), 0) as revenue,
              coalesce(sum(shipping_fee), 0) as shipping
            from public.orders where left(created_at, 10) between p_from and p_to group by 1) t
    ), '[]'::jsonb),
    'byWilaya', coalesce((
      select jsonb_agg(jsonb_build_object('wilaya_id', t.wilaya_id, 'wilaya_name', t.wilaya_name,
        'orders', t.orders, 'revenue', t.revenue, 'shipping', t.shipping,
        'returns', t.returns, 'delivered', t.delivered) order by t.orders desc)
      from (select o.wilaya_id, o.wilaya_name, count(*) as orders,
              coalesce(sum(o.total), 0) as revenue, coalesce(sum(o.shipping_fee), 0) as shipping,
              sum(case when o.status like 'retour%' then 1 else 0 end) as returns,
              sum(case when o.status in ('livre_non_encaisse','encaisse_non_paye','paiements_prets','paye_et_archive') then 1 else 0 end) as delivered
            from public.orders o where left(o.created_at, 10) between p_from and p_to
            group by o.wilaya_id, o.wilaya_name) t
    ), '[]'::jsonb),
    'byProduct', coalesce((
      select jsonb_agg(jsonb_build_object('name', t.name, 'sku', t.sku, 'qty', t.qty,
                                          'revenue', t.revenue) order by t.revenue desc)
      from (select oi.name, oi.sku, sum(oi.qty) as qty, coalesce(sum(oi.line_total), 0) as revenue
            from public.order_items oi join public.orders o on o.id = oi.order_id
            where left(o.created_at, 10) between p_from and p_to
            group by oi.name, oi.sku order by revenue desc limit 50) t
    ), '[]'::jsonb),
    'byStatus', coalesce((
      select jsonb_agg(jsonb_build_object('status', t.status, 'count', t.count,
                                          'revenue', t.revenue) order by t.count desc)
      from (select coalesce(s.ecotrack_status, o.status) as status, count(*) as count,
              coalesce(sum(o.total), 0) as revenue
            from public.orders o left join public.shipments s on s.order_id = o.id
            where left(o.created_at, 10) between p_from and p_to group by 1) t
    ), '[]'::jsonb),
    'byDeliveryType', coalesce((
      select jsonb_agg(jsonb_build_object('kind', t.kind, 'count', t.count, 'shipping', t.shipping))
      from (select case when o.stop_desk = 1 then 'stopdesk' else 'home' end as kind,
              count(*) as count, coalesce(sum(o.shipping_fee), 0) as shipping
            from public.orders o where left(o.created_at, 10) between p_from and p_to
            group by 1) t
    ), '[]'::jsonb),
    'deliveryPerformance', coalesce((
      select jsonb_agg(jsonb_build_object('status', t.status, 'count', t.count,
                                          'delivery_fees', t.delivery_fees) order by t.count desc)
      from (select s.ecotrack_status as status, count(*) as count,
              coalesce(sum(s.delivery_fee), 0) as delivery_fees
            from public.shipments s join public.orders o on o.id = s.order_id
            where left(o.created_at, 10) between p_from and p_to
              and s.tracking is not null and s.tracking <> ''
            group by s.ecotrack_status) t
    ), '[]'::jsonb)
  );
end $$;

-- ── قائمة الطلبيات مع الفلاتر (صفحة واحدة + العدد + التوزيع) ───────
create or replace function public.orders_page(
  p_q text default null,
  p_statuses text[] default null,
  p_wilaya integer default null,
  p_pushed integer default null,          -- null = الكل · 1 = مرسلة · 0 = غير مرسلة
  p_start text default null,
  p_end text default null,
  p_payment text default null,
  p_delivery integer default null,        -- null = الكل · 1 = مكتب · 0 = منزل
  p_limit integer default 25,
  p_offset integer default 0
)
returns jsonb
language plpgsql stable
as $$
declare
  v_q text;
begin
  v_q := lower(coalesce(p_q, ''));
  return jsonb_build_object(
    'orders', coalesce((
      with base as (
        select o.*, s.tracking, s.ecotrack_status, s.type as ship_type, s.pushed_at,
               s.validated_at, s.return_asked_at, s.last_activity, s.last_activity_at,
               (select count(*) from public.order_items oi where oi.order_id = o.id) as items_count
        from public.orders o
        left join public.shipments s on s.order_id = o.id
        where
          (p_q is null
            or lower(o.order_number) like '%' || v_q || '%'
            or lower(o.customer_name) like '%' || v_q || '%'
            or o.phone like '%' || p_q || '%'
            or s.tracking like '%' || p_q || '%'
            or s.reference like '%' || p_q || '%')
          and (p_statuses is null or o.status = any (p_statuses) or s.ecotrack_status = any (p_statuses))
          and (p_wilaya is null or o.wilaya_id = p_wilaya)
          and (p_pushed is null
            or (p_pushed = 1 and s.tracking is not null and s.tracking <> '')
            or (p_pushed = 0 and (s.tracking is null or s.tracking = '')))
          and (p_start is null or left(o.created_at, 10) >= p_start)
          and (p_end is null or left(o.created_at, 10) <= p_end)
          and (p_payment is null or o.payment_status = p_payment)
          and (p_delivery is null or o.stop_desk = p_delivery)
      )
      select jsonb_agg(row_to_json(t) order by t.id desc)
      from (select * from base order by id desc limit greatest(p_limit, 1) offset greatest(p_offset, 0)) t
    ), '[]'::jsonb),
    'total', (
      select count(*)
      from public.orders o left join public.shipments s on s.order_id = o.id
      where
        (p_q is null
          or lower(o.order_number) like '%' || v_q || '%'
          or lower(o.customer_name) like '%' || v_q || '%'
          or o.phone like '%' || p_q || '%'
          or s.tracking like '%' || p_q || '%'
          or s.reference like '%' || p_q || '%')
        and (p_statuses is null or o.status = any (p_statuses) or s.ecotrack_status = any (p_statuses))
        and (p_wilaya is null or o.wilaya_id = p_wilaya)
        and (p_pushed is null
          or (p_pushed = 1 and s.tracking is not null and s.tracking <> '')
          or (p_pushed = 0 and (s.tracking is null or s.tracking = '')))
        and (p_start is null or left(o.created_at, 10) >= p_start)
        and (p_end is null or left(o.created_at, 10) <= p_end)
        and (p_payment is null or o.payment_status = p_payment)
        and (p_delivery is null or o.stop_desk = p_delivery)
    ),
    'stats', coalesce((
      select jsonb_agg(jsonb_build_object('st', t.st, 'c', t.c) order by t.c desc)
      from (select coalesce(s.ecotrack_status, o.status) as st, count(*) as c
            from public.orders o left join public.shipments s on s.order_id = o.id
            group by 1) t
    ), '[]'::jsonb)
  );
end $$;

-- ── إحصائيات العملاء (عدد الطلبيات وإجمالي المشتريات لكل هاتف) ─────
create or replace function public.customers_stats(p_phones text[])
returns table (phone text, orders_count bigint, total_spent double precision)
language sql stable
as $$
  select o.phone,
         count(*) as orders_count,
         coalesce(sum(o.total), 0)::float8 as total_spent
  from public.orders o
  where o.phone = any (p_phones)
  group by o.phone;
$$;

-- ── تعديل المخزون زيادة/نقصاناً بدون ما تحت الصفر ─────────────────
create or replace function public.product_adjust_stock(p_id bigint, p_delta integer)
returns void
language sql
as $$
  update public.products
  set stock = greatest(0, stock + p_delta),
      updated_at = public.app_now()
  where id = p_id;
$$;

-- ── عدّاد الجداول (صفحة الإعدادات) ─────────────────────────────────
create or replace function public.table_counts()
returns jsonb
language plpgsql stable
as $$
begin
  return jsonb_build_object(
    'orders',            (select count(*) from public.orders),
    'order_items',       (select count(*) from public.order_items),
    'products',          (select count(*) from public.products),
    'customers',         (select count(*) from public.customers),
    'categories',        (select count(*) from public.categories),
    'shipments',         (select count(*) from public.shipments),
    'order_events',      (select count(*) from public.order_events),
    'wilayas',           (select count(*) from public.wilayas),
    'communes',          (select count(*) from public.communes),
    'desks',             (select count(*) from public.desks),
    'shipping_fees',     (select count(*) from public.shipping_fees),
    'ecotrack_products', (select count(*) from public.ecotrack_products),
    'activity_log',      (select count(*) from public.activity_log),
    'users',             (select count(*) from public.users)
  );
end $$;

-- ── عدّاد بيانات المزامنة (لوحة الشحن) ────────────────────────────
create or replace function public.sync_counts()
returns jsonb
language plpgsql stable
as $$
begin
  return jsonb_build_object(
    'wilayas',   (select count(*) from public.wilayas),
    'communes',  (select count(*) from public.communes),
    'desks',     (select count(*) from public.desks),
    'fees',      (select count(*) from public.shipping_fees),
    'products',  (select count(*) from public.ecotrack_products)
  );
end $$;

-- ── أذونات تنفيذ الدوال ────────────────────────────────────────────
grant execute on function
  public.app_now(),
  public.dashboard_data(integer),
  public.reports_data(text, text),
  public.orders_page(text, text[], integer, integer, text, text, text, integer, integer, integer),
  public.customers_stats(text[]),
  public.product_adjust_stock(bigint, integer),
  public.table_counts(),
  public.sync_counts()
to anon, authenticated;
